@startuml(id=ComponentWithContainersAndBoundaries)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/kotlin.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/postgresql.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/rocksdb.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title My Software System - New Backend App - Components
caption Test component view

SHOW_PERSON_OUTLINE()
LAYOUT_LEFT_RIGHT()

AddRelTag("async relationship", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $lineStyle = DashedLine())

Container_Boundary("MySoftwareSystem.FrontendApp_boundary", "Frontend App") {
  Component(MySoftwareSystem.FrontendApp.SPA, "SPA", "", "Single Page Application", "")
}
Container_Boundary("MySoftwareSystem.NewBackendApp_boundary", "New Backend App") {
  ComponentDb(MySoftwareSystem.NewBackendApp.Cache, "Cache", "RocksDB", "In Memory DB", "rocksdb", $link="https://google.de")
  WithoutPropertyHeader()
  AddProperty("jdbcUrl", "someurl")
  Component(MySoftwareSystem.NewBackendApp.MyRepo, "MyRepo", "Kotlin, JDBC", "Provides CRUD operations for data", "")
  Component(MySoftwareSystem.NewBackendApp.MyRestController, "MyRestController", "REST", "Provides data via rest", "")
  Component(MySoftwareSystem.NewBackendApp.MyService, "MyService", "", "Does implement some logic", "kotlin", $link="https://google.de")
}
ContainerDb(MySoftwareSystem.Database, "Database", "postgres", "some database", "postgresql")
Rel(MySoftwareSystem.NewBackendApp.MyRepo, MySoftwareSystem.Database, "gets data from")
Rel(MySoftwareSystem.NewBackendApp.MyRestController, MySoftwareSystem.NewBackendApp.MyService, "calls")
Rel(MySoftwareSystem.NewBackendApp.MyService, MySoftwareSystem.NewBackendApp.Cache, "uses")
Rel(MySoftwareSystem.NewBackendApp.MyService, MySoftwareSystem.NewBackendApp.MyRepo, "gets notified", $tags="async relationship")
Rel(MySoftwareSystem.FrontendApp.SPA, MySoftwareSystem.NewBackendApp.MyRestController, "gets data from")

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 150
SHOW_LEGEND(true)

@enduml