@startuml(id=ContainerWithoutBoundary)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/android-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/docker-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/graphql.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/kafka.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/postgresql.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title My Software System - Containers
caption Test container view

LAYOUT_TOP_DOWN()

AddRelTag("async relationship", $lineStyle=DashedLine(), $legendText=async relationship (dashed))

Person_Ext(AndroidUser, "Android User", "some Android user", $sprite="android-icon")
ContainerQueue_Ext(Broker.mytopic, "my.topic", "", "external topic", $sprite="kafka")
Container_Ext(GraphQL.ExternalSchema, "External Schema", "", "Schema provided by another team", "")
Container(GraphQL.InternalSchema, "Internal Schema", "", "Schema provided by our app", "")
WithoutPropertyHeader()
AddProperty("prop 1", "value 1")
Person(Maintainer, "Maintainer", "some employee", "", $link="https://www.google.de")
Container(MySoftwareSystem.App, "App", "Android", "android app", $sprite="android-icon")
WithoutPropertyHeader()
AddProperty("prop 1", "value 1")
Container(MySoftwareSystem.BackendApp, "Backend App", "Kotlin", "some backend app", $sprite="docker-icon", $link="https://www.google.de")
ContainerDb(MySoftwareSystem.Database, "Database", "postgres", "some database", $sprite="postgresql")

Rel(AndroidUser, MySoftwareSystem.App, "uses app")
Rel(MySoftwareSystem.App, GraphQL.InternalSchema, "request data using", "GraphQL", $sprite="graphql", $link="https://graphql.org/")
Rel_R(MySoftwareSystem.BackendApp, MySoftwareSystem.Database, "CRUD", "JPA")
Rel(MySoftwareSystem.BackendApp, GraphQL.InternalSchema, "provides subgraph to")
Rel(MySoftwareSystem.BackendApp, Broker.mytopic, "reads topic", "Avro", $tags="async relationship")
Rel_U(GraphQL.ExternalSchema, GraphQL.InternalSchema, "extends schema")
Rel(Maintainer, MySoftwareSystem.BackendApp, "Admin UI", "REST")
@enduml