@startuml(id=PersonStyleTest)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title My Software System - System Context
caption PersonStyleTest

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

AddPersonTag(special person, $sprite="img:https://plantuml.com/logo3.png{scale=0.4}", $bgColor=#fbbccf, $fontColor=#ff0000, $borderColor=#0000ff, $borderStyle=DashedLine(), $borderThickness=4, $shadowing=true, $shape=RoundedBoxShape(), $legendSprite="&compass{scale=3.0}", $legendText=this is a person)
System(MySoftwareSystem, "My Software System", "system", "", $tags="System Style")
Person(TestPerson, "Test Person", "", "", $tags="special person", $link="www.google.com")

Rel(TestPerson, MySoftwareSystem, "uses")

SHOW_LEGEND(true)

@enduml