@startuml(id=DynamicStyleSequenceTest)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/postgresql.puml
title My Software System - Dynamic
caption DynamicStyleSequenceTest

SHOW_PERSON_OUTLINE()

AddElementTag(Container Style, $sprite="postgresql{scale=0.5,color=#008000}", $bgColor=#ffffff, $fontColor=#ff0000, $borderColor=#800080, $borderStyle=DottedLine(), $borderThickness=5, $shadowing=false, $shape=RoundedBoxShape(), $techn=REST, $legendSprite="&compass", $legendText=this is a legend container)
AddBoundaryTag(Boundary Style, $bgColor=#00ffff, $fontColor=#008000, $borderColor=#ff0000, $borderStyle=DottedLine(), $borderThickness=4, $shadowing=false, $legendText=this is a system)
AddPersonTag(Person Style, $bgColor=#00ff00, $fontColor=#0000ff, $borderColor=#ff0000, $borderStyle=DashedLine(), $borderThickness=4, $shadowing=false, $shape=EightSidedShape(), $legendText=this is a person)
System_Boundary(MySoftwareSystem, My Software System, $tags="System Style+Boundary Style")
  Container(MySoftwareSystem.MyContainer, "My Container", "", "container", "", $tags="Container Style+Boundary Style")
Boundary_End()
Person(Person, "Person", "", "", $tags="Person Style")
Rel(Person, MySoftwareSystem.MyContainer, "1 uses" )

SHOW_LEGEND(true)

@enduml