@startuml(id=SystemStyleTest)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/android-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/apple.puml
title My Software System - System Context
caption SystemStyleTest

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

AddRelTag("Dependency Style", $sprite="android-icon{scale=1.3,color=#008000}", $lineColor=#008000, $textColor=#aa9999, $techn=Android, $lineStyle=DottedLine(), $lineThickness=2, $legendSprite="android-icon{scale=0.3,color=#008000}", $legendText=Android user uses)
AddElementTag("System Style", $sprite="img:https://plantuml.com/logo3.png{scale=0.4}", $bgColor=#000000, $fontColor=#ffff00, $borderColor=#008000, $borderStyle=DashedLine(), $borderThickness=4, $shadowing=true, $shape=EightSidedShape(), $techn=Kafka, $legendSprite="&compass{scale=3.0}", $legendText=this is a legend)
AddPersonTag("Person Style", $sprite="apple{scale=0.5,color=#008000}", $bgColor=#00ff00, $fontColor=#0000ff, $borderColor=#ff0000, $borderStyle=DashedLine(), $borderThickness=4, $shadowing=false, $shape=EightSidedShape(), $legendText=this is a apple)

System(MySoftwareSystem, "My Software System", "system", "", $tags="System Style+Boundary Style")
Person(Person, "Person", "", "", $tags="Person Style")

Rel(Person, MySoftwareSystem, "uses system", $tags="Dependency Style")

SHOW_LEGEND(true)

@enduml