@startuml(id=SequenceView)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

title Dynamic View: Software System 1
caption A test Dynamic View

SHOW_PERSON_OUTLINE()

Container(SoftwareSystem1.Container1System1, "Container 1 System 1", "", "")
Container(SoftwareSystem1.Container2System1, "Container 2 System 1", "", "Some description")
Person(Actor, "Actor", "")
Rel(SoftwareSystem1.Container1System1, SoftwareSystem1.Container2System1, "1 calls" )
Rel(SoftwareSystem1.Container2System1, SoftwareSystem1.Container1System1, "2 returns" )
Rel(SoftwareSystem1.Container1System1, Actor, "3 shows results" )

SHOW_LEGEND(true)

@enduml