@startuml(id=ContextDefault)
!define GILBARBARA_PNG_URL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/pngs
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl <logos/android-icon>

title System Context View: Software System 1
caption A test Landscape

SHOW_PERSON_OUTLINE()
LAYOUT_LEFT_RIGHT()

WithoutPropertyHeader()
AddProperty("prop 1", "value 1")
Person(Actor, "Actor", "", $link="https://www.google.de")
System_Ext(SoftwareSystem0, "Software System 0", "Description 0")
System(SoftwareSystem1, "Software System 1", "Description 1", $sprite="android-icon", $link="https://www.android.com")

Rel(Actor, SoftwareSystem0, "deletes", "gRPC")
WithoutPropertyHeader()
AddProperty("prop", "val")
Rel(Actor, SoftwareSystem1, "creates", "HTTP", $sprite="img:GILBARBARA_PNG_URL/html-5.png", $link="https://de.wikipedia.org/wiki/Hypertext_Transfer_Protocol")
Rel(SoftwareSystem0, SoftwareSystem1, "0 used by 1")

SHOW_FLOATING_LEGEND(LEGEND, false)

@enduml