@startuml(id=SystemLandscapeDefault)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/android-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/docker-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/html-5.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title System Landscape
caption A test Landscape

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

SetPropertyHeader("Property", "Value")
AddProperty("prop key0", "prop value0")
AddProperty("prop key1", "prop value1")
AddProperty("prop key2", "prop value2")
System(SoftwareSystem2, "Software System 2", "Description 2", "docker-icon", $link="https://www.docker.com/")


System(SoftwareSystem1, "Software System 1", "Description 1", "android-icon", $link="https://www.android.com")
System_Ext(SoftwareSystem0, "Software System 0", "Description 0", "")
SetPropertyHeader("Property", "Value")
AddProperty("prop key0", "prop value0")
AddProperty("prop key1", "prop value1")
AddProperty("prop key2", "prop value2")
System(SoftwareSystem2, "Software System 2", "Description 2", "docker-icon", $link="https://www.docker.com/")
WithoutPropertyHeader()
AddProperty("prop 1", "value 1")
Person(Actor, "Actor", "", "", $link="https://www.google.de")

Rel(Actor, SoftwareSystem0, "deletes", "gRPC")
WithoutPropertyHeader()
AddProperty("prop", "val")
Rel(Actor, SoftwareSystem1, "creates", "HTTP", $sprite=html-5, $link="https://de.wikipedia.org/wiki/Hypertext_Transfer_Protocol")
Rel(SoftwareSystem0, SoftwareSystem1, "0 used by 1")
Rel(SoftwareSystem2, SoftwareSystem0, "2 uses 1")

SHOW_LEGEND(true)

@enduml