@startuml(id=DynamicWithBoundary)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Reporting Service - Dynamic
caption This diagram shows what happens when a customer updates their details

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

System_Boundary(CustomerInformationSystem, Customer Information System) {
  Container_Boundary("CustomerInformationSystem.ReportingService_boundary", "Reporting Service") {
    Component(CustomerInformationSystem.ReportingService.ReportingController, "Reporting Controller", "REST", "Reporting Controller", "")
    Component(CustomerInformationSystem.ReportingService.ReportingRepository, "Reporting Repository", "JDBC", "Reporting repository", "")
  }
}
RelIndex(1,CustomerInformationSystem.ReportingService.ReportingController, CustomerInformationSystem.ReportingService.ReportingRepository, "Stores entity")

SHOW_LEGEND(true)

@enduml