@startuml(id=Container)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/android-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/docker-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/kafka.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/postgresql.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title My Software System - Containers
caption Test container view

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

WithoutPropertyHeader()
AddProperty("prop 1", "value 1")
Person(7, "Maintainer", "some employee", "", $link="https://www.google.de")
Person_Ext(16, "User", "some user", "android-icon")
System_Boundary(1_boundary, My Software System) {
  Container(3, "App", "Android", "android app", "android-icon")
  WithoutPropertyHeader()
  AddProperty("prop 1", "value 1")
  Container(2, "Backend App", "Kotlin", "some backend app", "docker-icon", $link="https://www.google.de")
  ContainerDb(5, "Database", "postgres", "some database", "postgresql")
  ContainerQueue_Ext(11, "Topic: my.topic", "", "external topic", "kafka")
}
Rel_D(3, 2, "desc", "Soap")
Rel_D(2, 5, "CRUD", "JPA")
Rel_D(2, 11, "reads topic", "Avro")
Rel_D(7, 2, "Admin UI", "REST")
Rel_D(16, 3, "uses app")

SHOW_LEGEND()

@enduml