@startuml(id=DependencyMode)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title System Landscape
caption Dependency Test

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

System(A, "A", "A", "")
System(B, "B", "B", "")
System(C, "C", "C", "")
System(D, "D", "C", "")
System(E, "E", "E", "")

Rel_Neighbor(A, D, "uses")
Rel_D(B, A, "uses")
Rel_D(C, A, "uses")
Rel_D(E, A, " ")

LAYOUT_WITH_LEGEND()

@enduml