@startuml(id=DependencyPosition)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title System Landscape
caption Dependency Test

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

System(A, "A", "A", "")
System(B, "B", "B", "")
System(C, "C", "C", "")
System(D, "D", "D", "")
System(E, "E", "E", "")

Rel_D(A, D, "uses")
Rel_U(B, A, "uses")
Rel_R(C, A, "uses")
Rel_L(E, A, "uses")

SHOW_LEGEND(true)

@enduml