@startuml(id=Deployment)
!includeurl https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist/AWSCommon.puml
!includeurl https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist/Containers/EKSCloud.puml
!includeurl https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist/GroupIcons/Cloudalt.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/apple.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/docker-icon.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/kafka.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/nginx.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/postgresql.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites/spring.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
title System container - Deployment - Default
caption A deployment diagram showing the environment.

SHOW_PERSON_OUTLINE()
LAYOUT_LEFT_RIGHT()

AddRelTag("async relationship", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $lineStyle = DashedLine())

SetPropertyHeader("Property", "Value", "Description")
AddProperty("Property1", "Value1", "Description1")
AddProperty("Property2", "Value2", "Description2")
Node(8, "AWS", "", "Production AWS environment", "Cloudalt"){
  Node(9, "AWS RDS", "", "", ""){
    WithoutPropertyHeader()
    AddProperty("region", "eu-central-1")
    ContainerDb(11, "Database", "PostgreSql", "Stores data", "postgresql")
    WithoutPropertyHeader()
    AddProperty("region", "eu-west-1")
    ContainerDb(10, "Failover Database", "PostgreSql", "Stores data", "postgresql")
  }
  Node(13, "EKS cluster", "", "", "EKSCloud"){
    Node(14, "my.web.app", "", "Web App POD", ""){
      Node(15, "Web App container", "", "", "docker-icon"){
        Node(18, "Jaeger Sidecar", "", "Jaeger sidecar sending Traces", "")
        Container(16, "Web Application", "Java and Spring MVC", "Spring Boot web application", "spring")
      }
    }
    SetPropertyHeader("Property", "value")
    AddProperty("IP", "10.234.234.132")
    Node(25, "Load Balancer", "nginx", "Nginx Load Balancer", "nginx", $link="https://www.google.de")
  }
}
Node(19, "Another AWS Account", "", "", "Cloudalt"){
  Node(20, "Jaeger Container", "", "", ""){
    Node(22, "Jaeger", "", "", "")
  }
}
Node(23, "Apple Device", "", "", "apple"){
  System_Ext(24, "iOS App", "iOS Application", "")
}
Rel_D(23, 25, "requests data from")
Rel_R(11, 10, "replicates data to")
SetPropertyHeader("key", "value")
AddProperty("ip", "10.234.12.13")
Rel_D(18, 20, "writes traces to", $sprite=kafka, $link="https://www.jaegertracing.io/", $tags="async relationship")
Rel_R(25, 15, "forwards requests to")
Rel_D(16, 11, "stores data in", "JDBC")

skinparam nodesep 50
skinparam ranksep 50
SHOW_LEGEND(true)

@enduml