@startuml(id=ComponentStyleTest)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title My Software System - My Container - Components
caption ComponentStyleTest

SHOW_PERSON_OUTLINE()
LAYOUT_TOP_DOWN()

AddElementTag(Component Style, $sprite="&compass", $bgColor=#ffffff, $fontColor=#ff0000, $borderColor=#800080, $borderStyle=DottedLine(), $borderThickness=5, $shadowing=false, $shape=RoundedBoxShape(), $techn=REST, $legendSprite="&compass", $legendText=this is a legend text)
Component(MySoftwareSystem.MyContainer.MyComponent, "My Component", "", "component", "", $tags="Component Style")

SHOW_LEGEND(true)

@enduml